apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
  namespace: eokarpova
  labels:
    app.kubernetes.io/name: person-service
    app.kubernetes.io/component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: person-service
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: person-service
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: app
          image: person-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: "/configs"
      volumes:
        - name: config
          configMap:
            name: person-service
